version: "3"
services:
  style-service:
    build: .
    image: "style-service-image:v1"
    container_name: "style-service"
    ports:
      - "8084:8084"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
        SPRING_DATA_MONGODB_URI: mongodb://mongodb-instance/solsticedb
  mongodb:
    image: mongo:latest
    container_name: "mongodb-instance"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"